connect to BankDatabase;

DROP PROCEDURE BANK.CUST_CRT;
DROP PROCEDURE BANK.CUST_LOGIN;
DROP PROCEDURE BANK.ACCT_OPN;
DROP PROCEDURE BANK.ACCT_CLS;
DROP PROCEDURE BANK.ACCT_DEP;
DROP PROCEDURE BANK.ACCT_WTH;
DROP PROCEDURE BANK.ACCT_TRX;
DROP PROCEDURE BANK.ADD_INTEREST;
DROP SPECIFIC FUNCTION BANK.ENCRYPT_PIN;
DROP TABLE BANK.ACCOUNT;
DROP TABLE BANK.CUSTOMER

terminate;
